# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:TANGhai1999@tcp(rm-bp1x9lppw27w472155o.mysql.rds.aliyuncs.com:3306)/go_gateway?charset=utf8&parseTime=true"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100